apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-helm
  namespace: bookinfo
spec:
  project: sample-project

  source:
    repoURL: https://github.com/sonalmallah12/argo-app.git
    targetRevision: main
    path: helm/bookinfo
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

